### ISSUE TITLE
Some records being assigned entries in CR_SUBJECT

### ISSUE THREAD

**Issue by pmusser** [mitodl/ocw_oer_export#121]
### Expected Behavior
When ocw_oer_export.csv generates, all entries should have a value in the CR_SUBJECT field.

### Current Behavior
On the most recent export, 52 rows do not have a value in CR_SUBJECT.

### Steps to Reproduce

1. Most recent csv attached for review ([ocw_oer_export (7).csv](https://github.com/user-attachments/files/17819050/ocw_oer_export.7.csv)), along with screenshot of csv in OpenRefine:
![Image](https://github.com/user-attachments/assets/f3a1292d-3f5d-4ffb-86df-c290c426820a)

### Possible Solution
I had a casual look through the records to see if there was some common thread (e.g. publish time or obvious subject that isn't mapping) but nothing jumped out at me. If someone can give me an export either as a csv or even a comment attached to this issue containing the course name, URL, and OCW subject headings for the entries that haven't been mapped, I can give mappings for them.

**Comment by pdpinch** [comment]
@ibrahimjaved12 can you take a look at this?

I looked at a couple of courses (e.g. [11.255](https://ocw.mit.edu/courses/11-255-negotiation-and-dispute-resolution-in-the-public-sector-spring-2021/)  and [15.760a](https://ocw.mit.edu/courses/15-760a-operations-management-spring-2002/)) and couldn't find any commonalities.

**Comment by ibrahimjaved12** [comment]
@pdpinch It looks like there are two `topics` fields in the MIT Learn API. And we may not be using the right one.

1. First `topics` field (represents MIT Learn topics for OCW courses):
```
"topics": [
            {
                "id": 720,
                "name": "Policy and Administration",
                "icon": "RiUserSearchLine",
                "parent": 712,
                "channel_url": "https://learn.mit.edu/c/topic/policy-and-administration/"
            },
            {
                "id": 698,
                "name": "Data Science, Analytics & Computer Technology",
                "icon": "RiLineChartLine",
                "parent": null,
                "channel_url": "https://learn.mit.edu/c/topic/data-science-analytics-computer-technology/"
            },
            {
                "id": 715,
                "name": "Economics",
                "icon": "RiUserSearchLine",
                "parent": 712,
                "channel_url": "https://learn.mit.edu/c/topic/economics/"
            },
        ],
```

2. Second `ocw_topics` field (specific to OCW topics):
```
"ocw_topics": [
            "Developmental Economics",
            "Economics",
            "Energy",
            "International Development",
            "Public Administration",
            "Public Policy",
            "Science and Technology Policy",
            "Security Studies",
            "Social Science",
            "Technology"
        ],
```

### The Issue

Currently, we are relying on the first `topics` field (MIT Learn topics), but I believe we should be using the second `ocw_topics` field (OCW-specific topics) ? I'm not sure how that got to be the case. But this is what is happening right now.

So it's not the courses that are problematic, it's that their ocw topics are being ignored. Can you please confirm this, so I can go ahead to creating a PR for this that uses `ocw_topics` instead.

### Some additional analysis
@pmusser I also performed an analysis of the OCW topics that might be useful.

In flattened structure, we have 335 OCW topics. And we have 328 OCW topics to OER Subject in the mapping file.

These are the OCW Topics that are missing OER Subject:

African American Studies (15 published courses)
Biomaterials (19 published courses)
Discrete Mathematics (39 published courses)
Italian (1 published course)
Nonfiction Prose (27 published courses)
Periodic Literature (8 published courses)
Project Management (29 published courses)
Quechua (0 published course)
Russian (1 published course)

However, these are 2nd-level subtopics or 3rd-level specialties in the unflattened hierarchy. Which means, their OER subject would also be populated by their parent category. So in essence, they should be populated, but regardless I wanted to share this in case we would like to have more specific subjects for them.
 
OCW Topics Hierarchy for Missing Topics:
```
- Humanities:
  - Language:
    - Italian .........3rd level missing speciality
    - Quechua .........3rd level missing speciality
    - Russian .........3rd level missing speciality
  - Literature:
    - Periodic Literature .........3rd level missing speciality
    - Nonfiction Prose .........3rd level missing speciality
- Business:
  - Project Management .........2nd level missing subtopic
- Engineering: 
  - Biological Engineering:
    - Biomaterials .........3rd level missing speciality
- Mathematics:
  - Discrete Mathematics .........2nd level missing subtopic
- Society:
  - African American Studies .........2nd level missing subtopic
```

### Analysis File

For a complete list of OCW courses and their mappings, please see this analysis file:
https://docs.google.com/spreadsheets/d/102Wdw1he5qVYh458XNTHwP5p9IVd0RBTRZx3piIgpTE/edit?gid=0#gid=0

### All OCW Topics Hierarchy file
[ocw_topics_hierarchy.txt](https://github.com/user-attachments/files/17945257/ocw_topics_hierarchy.txt)

In any case, this is the list of the 52 courses that do not have a `CR_SUBJECT` currently:
https://docs.google.com/spreadsheets/d/1UoMRJUVtLHIWechYEXWa6GZNTpRcOIQWS23wK_5_GFk/edit?gid=632809784#gid=632809784
